@coffeshop_HostAddress = http://localhost:5124

GET {{coffeshop_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{coffeshop_HostAddress}}/api/Product/1
Accept: application/json

###

GET {{coffeshop_HostAddress}}/api/Product/2
Accept: application/json

###
GET {{coffeshop_HostAddress}}/api/Product/3
Accept: application/json