@coffeshop_HostAddress = http://localhost:5124

GET {{coffeshop_HostAddress}}/weatherforecast/
Content-Type: application/json

###
GET {{coffeshop_HostAddress}}/api/Product/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6ImI3ZWE1ZjllLTQ0ZDUtNGNlYS1hNTcyLTdhZTMwODgyMGE1ZCIsImV4cCI6MTc1OTIxOTg4MywiaXNzIjoiQ29mZmVTaG9wRGVtbyIsImF1ZCI6IlRlc3QifQ.V7J2D1DBtfo0_1N19q5RiAFVvKWdz_Sniq9lOhIff4c
Content-Type: application/json

###

GET {{coffeshop_HostAddress}}/api/Product/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6IjE3ZTljMzRiLWMxZWEtNGU2MC1hZDYwLTIxOGNiZTEwYzhhNSIsImV4cCI6MTc1OTIxOTQ4OSwiaXNzIjoiQ29mZmVTaG9wRGVtbyIsImF1ZCI6IlRlc3QifQ.EiEkP4qokTUxwOSP35i6IZgVjvNm94AdLE6YiqM-XFE
Content-Type: application/json

###
GET {{coffeshop_HostAddress}}/api/Product/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImp0aSI6ImI3ZWE1ZjllLTQ0ZDUtNGNlYS1hNTcyLTdhZTMwODgyMGE1ZCIsImV4cCI6MTc1OTIxOTg4MywiaXNzIjoiQ29mZmVTaG9wRGVtbyIsImF1ZCI6IlRlc3QifQ.V7J2D1DBtfo0_1N19q5RiAFVvKWdz_Sniq9lOhIff4c
Content-Type: application/json


###
POST {{coffeshop_HostAddress}}/api/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "password123"
}